export const games = [{
    "albums": {
        "href": "https://api.spotify.com/v1/browse/new-releases?offset=0&limit=20",
        "items": [
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X"
                        },
                        "href": "https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X",
                        "id": "4q3ewBCX7sLwd24euuV69X",
                        "name": "Bad Bunny",
                        "type": "artist",
                        "uri": "spotify:artist:4q3ewBCX7sLwd24euuV69X"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/2d9BCZeAAhiZWPpbX9aPCW"
                },
                "href": "https://api.spotify.com/v1/albums/2d9BCZeAAhiZWPpbX9aPCW",
                "id": "2d9BCZeAAhiZWPpbX9aPCW",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273005ee342f4eef2cc6e8436ab",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02005ee342f4eef2cc6e8436ab",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851005ee342f4eef2cc6e8436ab",
                        "width": 64
                    }
                ],
                "name": "EL ÚLTIMO TOUR DEL MUNDO",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 16,
                "type": "album",
                "uri": "spotify:album:2d9BCZeAAhiZWPpbX9aPCW"
            },
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6"
                        },
                        "href": "https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6",
                        "id": "5YGY8feqx7naU7z4HrwZM6",
                        "name": "Miley Cyrus",
                        "type": "artist",
                        "uri": "spotify:artist:5YGY8feqx7naU7z4HrwZM6"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0BCjAmbM8ryCM9gxy5yW7h"
                },
                "href": "https://api.spotify.com/v1/albums/0BCjAmbM8ryCM9gxy5yW7h",
                "id": "0BCjAmbM8ryCM9gxy5yW7h",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b27350061ccded678a361a2009ec",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e0250061ccded678a361a2009ec",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d0000485150061ccded678a361a2009ec",
                        "width": 64
                    }
                ],
                "name": "Plastic Hearts",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 15,
                "type": "album",
                "uri": "spotify:album:0BCjAmbM8ryCM9gxy5yW7h"
            },
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/48eO052eSDcn8aTxiv6QaG"
                        },
                        "href": "https://api.spotify.com/v1/artists/48eO052eSDcn8aTxiv6QaG",
                        "id": "48eO052eSDcn8aTxiv6QaG",
                        "name": "NCT",
                        "type": "artist",
                        "uri": "spotify:artist:48eO052eSDcn8aTxiv6QaG"
                    }
                ],
                "available_markets": [
                    "CA",
                    "US"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/5Dq6jkYO5H7KzxXSazhLxs"
                },
                "href": "https://api.spotify.com/v1/albums/5Dq6jkYO5H7KzxXSazhLxs",
                "id": "5Dq6jkYO5H7KzxXSazhLxs",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273a8f520a58790e872d0007e2e",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02a8f520a58790e872d0007e2e",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851a8f520a58790e872d0007e2e",
                        "width": 64
                    }
                ],
                "name": "NCT RESONANCE Pt. 2 - The 2nd Album",
                "release_date": "2020-11-23",
                "release_date_precision": "day",
                "total_tracks": 21,
                "type": "album",
                "uri": "spotify:album:5Dq6jkYO5H7KzxXSazhLxs"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/30DhU7BDmF4PH0JVhu8ZRg"
                        },
                        "href": "https://api.spotify.com/v1/artists/30DhU7BDmF4PH0JVhu8ZRg",
                        "id": "30DhU7BDmF4PH0JVhu8ZRg",
                        "name": "Sabrina Claudio",
                        "type": "artist",
                        "uri": "spotify:artist:30DhU7BDmF4PH0JVhu8ZRg"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ"
                        },
                        "href": "https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ",
                        "id": "1Xyo4u8uXC1ZmMpatF05PJ",
                        "name": "The Weeknd",
                        "type": "artist",
                        "uri": "spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/4d5Ak9U5eZ3lU1JGfnMUdI"
                },
                "href": "https://api.spotify.com/v1/albums/4d5Ak9U5eZ3lU1JGfnMUdI",
                "id": "4d5Ak9U5eZ3lU1JGfnMUdI",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273b47ba4ac1f43f732a6696689",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02b47ba4ac1f43f732a6696689",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851b47ba4ac1f43f732a6696689",
                        "width": 64
                    }
                ],
                "name": "Christmas Blues (with The Weeknd)",
                "release_date": "2020-11-26",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:4d5Ak9U5eZ3lU1JGfnMUdI"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0H39MdGGX6dbnnQPt6NQkZ"
                        },
                        "href": "https://api.spotify.com/v1/artists/0H39MdGGX6dbnnQPt6NQkZ",
                        "id": "0H39MdGGX6dbnnQPt6NQkZ",
                        "name": "SAINt JHN",
                        "type": "artist",
                        "uri": "spotify:artist:0H39MdGGX6dbnnQPt6NQkZ"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
                        },
                        "href": "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
                        "id": "5K4W6rqBFWDnAN6FQUkS6x",
                        "name": "Kanye West",
                        "type": "artist",
                        "uri": "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/5lmqvqSTMlKqSrM8EtGmhe"
                },
                "href": "https://api.spotify.com/v1/albums/5lmqvqSTMlKqSrM8EtGmhe",
                "id": "5lmqvqSTMlKqSrM8EtGmhe",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2739b5a63c0cdc1d0d6f1f47e68",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e029b5a63c0cdc1d0d6f1f47e68",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048519b5a63c0cdc1d0d6f1f47e68",
                        "width": 64
                    }
                ],
                "name": "Smack DVD (feat. Kanye West)",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:5lmqvqSTMlKqSrM8EtGmhe"
            },
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/6icQOAFXDZKsumw3YXyusw"
                        },
                        "href": "https://api.spotify.com/v1/artists/6icQOAFXDZKsumw3YXyusw",
                        "id": "6icQOAFXDZKsumw3YXyusw",
                        "name": "Lil Yachty",
                        "type": "artist",
                        "uri": "spotify:artist:6icQOAFXDZKsumw3YXyusw"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/6ufaA5YvSGK3E9KnRFYvvo"
                },
                "href": "https://api.spotify.com/v1/albums/6ufaA5YvSGK3E9KnRFYvvo",
                "id": "6ufaA5YvSGK3E9KnRFYvvo",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273789e7bbd2cc0ae4085b4d59f",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02789e7bbd2cc0ae4085b4d59f",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851789e7bbd2cc0ae4085b4d59f",
                        "width": 64
                    }
                ],
                "name": "Lil Boat 3.5",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 27,
                "type": "album",
                "uri": "spotify:album:6ufaA5YvSGK3E9KnRFYvvo"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR"
                        },
                        "href": "https://api.spotify.com/v1/artists/2DlGxzQSjYe5N6G9nkYghR",
                        "id": "2DlGxzQSjYe5N6G9nkYghR",
                        "name": "Jennifer Lopez",
                        "type": "artist",
                        "uri": "spotify:artist:2DlGxzQSjYe5N6G9nkYghR"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/4Z31ZtSbHbEMQAi5ZArKiv"
                },
                "href": "https://api.spotify.com/v1/albums/4Z31ZtSbHbEMQAi5ZArKiv",
                "id": "4Z31ZtSbHbEMQAi5ZArKiv",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b27373632159ed34cea1b9e0be5d",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e0273632159ed34cea1b9e0be5d",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d0000485173632159ed34cea1b9e0be5d",
                        "width": 64
                    }
                ],
                "name": "In The Morning",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:4Z31ZtSbHbEMQAi5ZArKiv"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2gduEC76ry33RVurAvT05p"
                        },
                        "href": "https://api.spotify.com/v1/artists/2gduEC76ry33RVurAvT05p",
                        "id": "2gduEC76ry33RVurAvT05p",
                        "name": "Nathan Dawe",
                        "type": "artist",
                        "uri": "spotify:artist:2gduEC76ry33RVurAvT05p"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3e7awlrlDSwF3iM0WBjGMp"
                        },
                        "href": "https://api.spotify.com/v1/artists/3e7awlrlDSwF3iM0WBjGMp",
                        "id": "3e7awlrlDSwF3iM0WBjGMp",
                        "name": "Little Mix",
                        "type": "artist",
                        "uri": "spotify:artist:3e7awlrlDSwF3iM0WBjGMp"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/5uFXAG4F9SX86RS5RHWDsx"
                },
                "href": "https://api.spotify.com/v1/albums/5uFXAG4F9SX86RS5RHWDsx",
                "id": "5uFXAG4F9SX86RS5RHWDsx",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273bdedb94e1631ee5523385584",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02bdedb94e1631ee5523385584",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851bdedb94e1631ee5523385584",
                        "width": 64
                    }
                ],
                "name": "No Time For Tears",
                "release_date": "2020-11-26",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:5uFXAG4F9SX86RS5RHWDsx"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0huGjMyP507tBCARyzSkrv"
                        },
                        "href": "https://api.spotify.com/v1/artists/0huGjMyP507tBCARyzSkrv",
                        "id": "0huGjMyP507tBCARyzSkrv",
                        "name": "Cordae",
                        "type": "artist",
                        "uri": "spotify:artist:0huGjMyP507tBCARyzSkrv"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/2r50ydw2FOuiffavTsvXAM"
                },
                "href": "https://api.spotify.com/v1/albums/2r50ydw2FOuiffavTsvXAM",
                "id": "2r50ydw2FOuiffavTsvXAM",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2738da54461b711e3bee831dcfa",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e028da54461b711e3bee831dcfa",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048518da54461b711e3bee831dcfa",
                        "width": 64
                    }
                ],
                "name": "The Parables",
                "release_date": "2020-11-24",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:2r50ydw2FOuiffavTsvXAM"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/1r1uxoy19fzMxunt3ONAkG"
                        },
                        "href": "https://api.spotify.com/v1/artists/1r1uxoy19fzMxunt3ONAkG",
                        "id": "1r1uxoy19fzMxunt3ONAkG",
                        "name": "Phoebe Bridgers",
                        "type": "artist",
                        "uri": "spotify:artist:1r1uxoy19fzMxunt3ONAkG"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/7xoBevaHIAcXvYiLdqhQMC"
                },
                "href": "https://api.spotify.com/v1/albums/7xoBevaHIAcXvYiLdqhQMC",
                "id": "7xoBevaHIAcXvYiLdqhQMC",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2730a224ffbe81d687d7833c3b5",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e020a224ffbe81d687d7833c3b5",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048510a224ffbe81d687d7833c3b5",
                        "width": 64
                    }
                ],
                "name": "If We Make It Through December",
                "release_date": "2020-11-23",
                "release_date_precision": "day",
                "total_tracks": 4,
                "type": "album",
                "uri": "spotify:album:7xoBevaHIAcXvYiLdqhQMC"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/6Ad91Jof8Niiw0lGLLi3NW"
                        },
                        "href": "https://api.spotify.com/v1/artists/6Ad91Jof8Niiw0lGLLi3NW",
                        "id": "6Ad91Jof8Niiw0lGLLi3NW",
                        "name": "YUNGBLUD",
                        "type": "artist",
                        "uri": "spotify:artist:6Ad91Jof8Niiw0lGLLi3NW"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/6Er2phjif5umoFiEFAsUxR"
                },
                "href": "https://api.spotify.com/v1/albums/6Er2phjif5umoFiEFAsUxR",
                "id": "6Er2phjif5umoFiEFAsUxR",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2731dfd062efabbc51d1eaaebb2",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e021dfd062efabbc51d1eaaebb2",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048511dfd062efabbc51d1eaaebb2",
                        "width": 64
                    }
                ],
                "name": "mars",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:6Er2phjif5umoFiEFAsUxR"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/22vqVhfPJab5kkU9txDGX3"
                        },
                        "href": "https://api.spotify.com/v1/artists/22vqVhfPJab5kkU9txDGX3",
                        "id": "22vqVhfPJab5kkU9txDGX3",
                        "name": "Q",
                        "type": "artist",
                        "uri": "spotify:artist:22vqVhfPJab5kkU9txDGX3"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/4j8ZiT9TBNTylP578zuJRn"
                },
                "href": "https://api.spotify.com/v1/albums/4j8ZiT9TBNTylP578zuJRn",
                "id": "4j8ZiT9TBNTylP578zuJRn",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273c978f61715cbd794b0074742",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02c978f61715cbd794b0074742",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851c978f61715cbd794b0074742",
                        "width": 64
                    }
                ],
                "name": "Alone",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:4j8ZiT9TBNTylP578zuJRn"
            },
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5gCRApTajqwbnHHPbr2Fpi"
                        },
                        "href": "https://api.spotify.com/v1/artists/5gCRApTajqwbnHHPbr2Fpi",
                        "id": "5gCRApTajqwbnHHPbr2Fpi",
                        "name": "Juicy J",
                        "type": "artist",
                        "uri": "spotify:artist:5gCRApTajqwbnHHPbr2Fpi"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/6zFqKeygTGAmLEF2AXCfZO"
                },
                "href": "https://api.spotify.com/v1/albums/6zFqKeygTGAmLEF2AXCfZO",
                "id": "6zFqKeygTGAmLEF2AXCfZO",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273dc29366db864d23928c801de",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02dc29366db864d23928c801de",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851dc29366db864d23928c801de",
                        "width": 64
                    }
                ],
                "name": "THE HUSTLE CONTINUES",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 16,
                "type": "album",
                "uri": "spotify:album:6zFqKeygTGAmLEF2AXCfZO"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4xjJOu0MWVWuaDVZOy0Dx2"
                        },
                        "href": "https://api.spotify.com/v1/artists/4xjJOu0MWVWuaDVZOy0Dx2",
                        "id": "4xjJOu0MWVWuaDVZOy0Dx2",
                        "name": "Silver Sphere",
                        "type": "artist",
                        "uri": "spotify:artist:4xjJOu0MWVWuaDVZOy0Dx2"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0ZUUNzW2alJzw9JkRRiIfM"
                },
                "href": "https://api.spotify.com/v1/albums/0ZUUNzW2alJzw9JkRRiIfM",
                "id": "0ZUUNzW2alJzw9JkRRiIfM",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273c61a3ef214296f5fe4a9ba49",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02c61a3ef214296f5fe4a9ba49",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851c61a3ef214296f5fe4a9ba49",
                        "width": 64
                    }
                ],
                "name": "football game",
                "release_date": "2020-11-25",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:0ZUUNzW2alJzw9JkRRiIfM"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3klZnJvYGIbWritVwQD434"
                        },
                        "href": "https://api.spotify.com/v1/artists/3klZnJvYGIbWritVwQD434",
                        "id": "3klZnJvYGIbWritVwQD434",
                        "name": "Duncan Laurence",
                        "type": "artist",
                        "uri": "spotify:artist:3klZnJvYGIbWritVwQD434"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/6bm9QRIdbRMjsrSNVzj9E0"
                },
                "href": "https://api.spotify.com/v1/albums/6bm9QRIdbRMjsrSNVzj9E0",
                "id": "6bm9QRIdbRMjsrSNVzj9E0",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273a290193b79e8336bd8e54944",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02a290193b79e8336bd8e54944",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851a290193b79e8336bd8e54944",
                        "width": 64
                    }
                ],
                "name": "Arcade (feat. FLETCHER)",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:6bm9QRIdbRMjsrSNVzj9E0"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2WBJQGf1bT1kxuoqziH5g4"
                        },
                        "href": "https://api.spotify.com/v1/artists/2WBJQGf1bT1kxuoqziH5g4",
                        "id": "2WBJQGf1bT1kxuoqziH5g4",
                        "name": "Purple Disco Machine",
                        "type": "artist",
                        "uri": "spotify:artist:2WBJQGf1bT1kxuoqziH5g4"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5pN1DJhPFDKso4OtC0QhnB"
                        },
                        "href": "https://api.spotify.com/v1/artists/5pN1DJhPFDKso4OtC0QhnB",
                        "id": "5pN1DJhPFDKso4OtC0QhnB",
                        "name": "Mind Enterprises",
                        "type": "artist",
                        "uri": "spotify:artist:5pN1DJhPFDKso4OtC0QhnB"
                    }
                ],
                "available_markets": [
                    "GB",
                    "IE",
                    "US"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0fequ3nqlInmYUas1U2EJi"
                },
                "href": "https://api.spotify.com/v1/albums/0fequ3nqlInmYUas1U2EJi",
                "id": "0fequ3nqlInmYUas1U2EJi",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273dbba9bd7567edd47774a842c",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02dbba9bd7567edd47774a842c",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851dbba9bd7567edd47774a842c",
                        "width": 64
                    }
                ],
                "name": "Exotica",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 3,
                "type": "album",
                "uri": "spotify:album:0fequ3nqlInmYUas1U2EJi"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/28gNT5KBp7IjEOQoevXf9N"
                        },
                        "href": "https://api.spotify.com/v1/artists/28gNT5KBp7IjEOQoevXf9N",
                        "id": "28gNT5KBp7IjEOQoevXf9N",
                        "name": "Camilo",
                        "type": "artist",
                        "uri": "spotify:artist:28gNT5KBp7IjEOQoevXf9N"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm"
                        },
                        "href": "https://api.spotify.com/v1/artists/2oQX8QiMXOyuqbcZEFsZfm",
                        "id": "2oQX8QiMXOyuqbcZEFsZfm",
                        "name": "El Alfa",
                        "type": "artist",
                        "uri": "spotify:artist:2oQX8QiMXOyuqbcZEFsZfm"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0krfGu8Xf8xZGOeEcQUjai"
                },
                "href": "https://api.spotify.com/v1/albums/0krfGu8Xf8xZGOeEcQUjai",
                "id": "0krfGu8Xf8xZGOeEcQUjai",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273a82e8d3dc5cea65aca690beb",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02a82e8d3dc5cea65aca690beb",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851a82e8d3dc5cea65aca690beb",
                        "width": 64
                    }
                ],
                "name": "BEBÉ",
                "release_date": "2020-11-25",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:0krfGu8Xf8xZGOeEcQUjai"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/6L1XC7NrmgWRlwAeLJvVtA"
                        },
                        "href": "https://api.spotify.com/v1/artists/6L1XC7NrmgWRlwAeLJvVtA",
                        "id": "6L1XC7NrmgWRlwAeLJvVtA",
                        "name": "Sam Fischer",
                        "type": "artist",
                        "uri": "spotify:artist:6L1XC7NrmgWRlwAeLJvVtA"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/6OvECyR3eoMORZcXc2sptA"
                },
                "href": "https://api.spotify.com/v1/albums/6OvECyR3eoMORZcXc2sptA",
                "id": "6OvECyR3eoMORZcXc2sptA",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2733f567f92b47b3656ab9af7e9",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e023f567f92b47b3656ab9af7e9",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048513f567f92b47b3656ab9af7e9",
                        "width": 64
                    }
                ],
                "name": "For Now",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:6OvECyR3eoMORZcXc2sptA"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/14CHVeJGrR5xgUGQFV5BVM"
                        },
                        "href": "https://api.spotify.com/v1/artists/14CHVeJGrR5xgUGQFV5BVM",
                        "id": "14CHVeJGrR5xgUGQFV5BVM",
                        "name": "Fivio Foreign",
                        "type": "artist",
                        "uri": "spotify:artist:14CHVeJGrR5xgUGQFV5BVM"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/4P3x3MxVxNUBN0y7z98RC3"
                },
                "href": "https://api.spotify.com/v1/albums/4P3x3MxVxNUBN0y7z98RC3",
                "id": "4P3x3MxVxNUBN0y7z98RC3",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273efab602df7942bb34c202f3e",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02efab602df7942bb34c202f3e",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851efab602df7942bb34c202f3e",
                        "width": 64
                    }
                ],
                "name": "Trust",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 1,
                "type": "album",
                "uri": "spotify:album:4P3x3MxVxNUBN0y7z98RC3"
            },
            {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4sTFGCigAQIUiEy8wSSQNF"
                        },
                        "href": "https://api.spotify.com/v1/artists/4sTFGCigAQIUiEy8wSSQNF",
                        "id": "4sTFGCigAQIUiEy8wSSQNF",
                        "name": "Granger Smith",
                        "type": "artist",
                        "uri": "spotify:artist:4sTFGCigAQIUiEy8wSSQNF"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AL",
                    "AR",
                    "AT",
                    "AU",
                    "BA",
                    "BE",
                    "BG",
                    "BH",
                    "BO",
                    "BR",
                    "BY",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HR",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JO",
                    "JP",
                    "KW",
                    "KZ",
                    "LB",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MK",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PS",
                    "PT",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "SA",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SV",
                    "TH",
                    "TN",
                    "TR",
                    "TW",
                    "UA",
                    "US",
                    "UY",
                    "VN",
                    "XK",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/18pN6ovdqBSdM3R8SVnlTe"
                },
                "href": "https://api.spotify.com/v1/albums/18pN6ovdqBSdM3R8SVnlTe",
                "id": "18pN6ovdqBSdM3R8SVnlTe",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273c13a073f5a933e2c652e8aa3",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02c13a073f5a933e2c652e8aa3",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851c13a073f5a933e2c652e8aa3",
                        "width": 64
                    }
                ],
                "name": "Country Things, Vol. 2",
                "release_date": "2020-11-27",
                "release_date_precision": "day",
                "total_tracks": 8,
                "type": "album",
                "uri": "spotify:album:18pN6ovdqBSdM3R8SVnlTe"
            }
        ],
    }
}
]